version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'final'
      MONGO_INITDB_ROOT_USERNAME: 'usr-inscription-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-inscription-mongo'
    ports:
      - 27025:27017
    expose:
      - 27025
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
   